parameters:
    admin_email: '%env(ADMIN_EMAIL)%'
    pizza_images_directory: '%kernel.project_dir%/public/uploads/pizzas'
    menu_images_directory: '%kernel.project_dir%/public/uploads/menus'
    stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'
    stripe_webhook_secret: '%env(STRIPE_WEBHOOK_SECRET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\EmailService:
        arguments:
            $adminEmail: '%admin_email%'

    Stripe\StripeClient:
        arguments:
            - '%env(STRIPE_SECRET_KEY)%'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\EventSubscriber\StripeSubscriber:
        tags: ['kernel.event_subscriber']